### ISSUE TITLE
Launch in Geothermal Prospector

### ISSUE THREAD

**Issue by ccaudill** [usgin/jsCSWwidget#2]
Per email on 5/1 and 5/13, how will data retrieved from the widget be loaded into the Geothermal Prospector (https://maps.nrel.gov/geothermal-prospector/) fluidly, while still allowing it to be customizable to other applications?

**Comment by smrgeoinfo** [comment]
I think this is a prospector development question at this point. We need feed back on the portability/plugability of the widget.

**Comment by ccaudill** [comment]
@smrazgs Please see Dan's email from 5/13 - he believes this coding should be done on the widget end

**Comment by ccaudill** [comment]
Per Dan's email request:

>  There will need to be a clearly indicated button on the interface
> that allows it to launch instigate the launch of the layer in the
> prospector. This button can simply alert something at the monument, but
> it needs to be part of the interface design in any case.

...the main purpose of

> this tool is to load data into the prospector, I’m a bit confused by
> the load button being an afterthought in the delivery and design. Also,
> I feel that some of the options are not useful in this purpose.

**Comment by ccaudill** [comment]
WMS and WFS would be added at https://maps.nrel.gov/geothermal-prospector/

**Comment by smrgeoinfo** [comment]
I think what we need to do is add a button on the demo page to 'display in geothermal prospector' that does the same thing the button in CKAN search result does (e.g. see http://search.geothermaldata.org/dataset/canada-borehole-temperaturese403d). The web page that is hosting the widget would have to get the widget response and use that to construct the Geothermal prospector call, with in the Canada-borehole example above is:

```
https://maps.nrel.gov/geothermal-prospector/#/?baselayer=6&zoomlevel=3&wmsHost=http%3A%2F%2Fservices.azgs.az.gov%2Farcgis%2Fservices%2FNGDS%2FCanadaBoreholeTemperatures%2FMapServer%2FWmsServer%3F&wmsLayerName=BoreholeTemperature&wfsHost=http%3A%2F%2Fservices.azgs.az.gov%2Farcgis%2Fservices%2FNGDS%2FCanadaBoreholeTemperatures%2FMapServer%2FWFSServer%3F&wfsFeatureTypeName=aasg:BoreholeTemperature
```

or, decoded and formatted some:

```
https://maps.nrel.gov/geothermal-prospector/#/?baselayer=6
&zoomlevel=3
&wmsHost=http://services.azgs.az.gov/arcgis/services/NGDS/CanadaBoreholeTemperatures/MapServer/WmsServer?
&wmsLayerName=BoreholeTemperature
&wfsHost=http://services.azgs.az.gov/arcgis/services/NGDS/CanadaBoreholeTemperatures/MapServer/WFSServer?
&wfsFeatureTypeName=aasg:BoreholeTemperature
```

I know WenWen's team is already over budget, so I'll see if Jessica can figure out how to add the button. @wushengcq  -- I'm assuming the html in the repository at https://github.com/usgin/jsCSWwidget/blob/master/test/ui-test.htm is the code for that test page?

**Comment by wushengcq** [comment]
@smrazgs  -- yes, you are right. 
https://github.com/usgin/jsCSWwidget/blob/master/test/ui-test.htm is the code for that test page.

I have a question about the construction of Geothermal prospector call.
There is one **wmsLayerName** and one **wfsFeatureTypeName** int parameters,  whenever the widget return a WMS/WFS server which contains multiple layers, how to build a url making prospector map to load all the layers at startup ?

**Comment by jessicagood** [comment]
Dan only wants the text box alert with the results (which is already implemented) when clicking on `Add To Map` and he will integrate into Geothermal Prospector from there. We can revisit this later if he changes his mind.
