### ISSUE TITLE
Change Catalog CSW URL

### ISSUE THREAD

**Issue by ccaudill** [usgin/jsCSWwidget#3]
Edit the catalog choice from:
http://catalog.usgin.org/geoportal/csw
to:
http://catalog.usgin.org/geothermal/csw

It is the most updated, and the Geportal from which NGDS is harvested.

**Comment by wushengcq** [comment]
I have update the lib/jsCSWwidget/conf.xml file, and add http://catalog.usgin.org/geothermal/csw to the catalog choices.

**Comment by ccaudill** [comment]
Excellent!
