### ISSUE TITLE
WMS and WFS check boxes

### ISSUE THREAD

**Issue by smrgeoinfo** [usgin/jsCSWwidget#5]
WMS should be checked by default
the labels need to be something more informative to regular users-- maybe 'map service' and 'data service'. 
If mousing over the check boxes could trigger a pop up with an explanation of what they do that would be a good thing.

**Comment by jessicagood** [comment]
WMS checkbox checked and disabled by default with commit 616f739c06877e1037fbc2c1541d3389f7a927ec
WFS checkbox checked by default with commit 746962f6a00e5850e5a061ee2feef8dfc042e61a
