### ISSUE TITLE
results don't seem to have WFS information

### ISSUE THREAD

**Issue by smrgeoinfo** [usgin/jsCSWwidget#6]
the results JSON that is displayed does not include the WFS end point URL or feature type name information. This should be included in the response from the widget

**Comment by jessicagood** [comment]
These look like they are there to me. 

```
[{"linkURL":"http://services.azgs.az.gov/ArcGIS/services/aasggeothermal/AZActiveFaults/MapServer/WFSServer","APILabel":"OGC:WFS","linkParameters":[{"linkParameterLabel":"featureType","linkParameterValue":"aasg:ActiveFault"},
```

![capture](https://cloud.githubusercontent.com/assets/1493985/8316314/f9214d24-19aa-11e5-8cf0-599ab172a1a0.PNG)
