### ISSUE TITLE
add layer to map button needs to be more obvious

### ISSUE THREAD

**Issue by smrgeoinfo** [usgin/jsCSWwidget#7]
It took me awhile to figure out the little plus sign in the lower right is what returns information to the caller.
should have a more obvious 'Add Layer' button; seems like default for clicking that should be to close the window; maybe add a check box to 'keep window open to add multiple layers' to change behavior to require clicking the 'X' in upper right to get the window to close?

**Comment by jessicagood** [comment]
Changed to button with text in commit 353833ed89c6273232ddcbf80d49d838e1d5f8dd
