### ISSUE TITLE
launch in Prospector button on the ui-test page

### ISSUE THREAD

**Issue by smrgeoinfo** [usgin/jsCSWwidget#8]
button that opens the widget, and takes result from widget when user clicks add layer, creates NREL Geothermal Prospector request URL to display the layer. See discussion at bottom of issue #2 for more info on the URL

**Comment by jessicagood** [comment]
As per an email from Dan he only wants the text box alert with the results (which is already implemented) when clicking on Add To Map and he will integrate into Geothermal Prospector from there. We can revisit this later if he changes his mind.
